export default function PrivacyPage() {
    return (
      <div className="page-fade" style={{ maxWidth: 640, margin: '48px auto', padding: '0 20px' }}>
        <a href="/" style={{ display: 'inline-block', marginBottom: 20, fontSize: 13 }}>← Back to home</a>
        <h1 style={{ fontSize: 28, marginBottom: 24 }}>Privacy Policy</h1>
  
        <div className="card" style={{ fontSize: 14, lineHeight: 1.7, color: 'var(--text-muted)' }}>
          <p style={{ marginBottom: 16 }}><i>Last updated: {new Date().toLocaleDateString('en-US', { month: 'long', day: 'numeric', year: 'numeric' })}</i></p>
  
          <h4 style={{ color: 'var(--text)', marginTop: 20, marginBottom: 8 }}>What we collect</h4>
          <p style={{ marginBottom: 16 }}>
            We collect the information you provide directly: your email address, a username, and any content you create in the app (tasks, session labels, comments, and similar). We also collect usage data automatically generated by using the app, such as focus session times, XP earned, and activity you choose to share.
          </p>
  
          <h4 style={{ color: 'var(--text)', marginTop: 20, marginBottom: 8 }}>How we use it</h4>
          <p style={{ marginBottom: 16 }}>
            Your data is used to operate the app: authenticating you, displaying your progress, enabling social features like friends and leaderboards, and improving the product. We do not sell your personal data to third parties.
          </p>
  
          <h4 style={{ color: 'var(--text)', marginTop: 20, marginBottom: 8 }}>What's visible to others</h4>
          <p style={{ marginBottom: 16 }}>
            Your username and any activity you mark as public (shared focus sessions) are visible to your friends within the app. Content you keep private is visible only to you. We do not display your email address to other users.
          </p>
  
          <h4 style={{ color: 'var(--text)', marginTop: 20, marginBottom: 8 }}>Third-party services</h4>
          <p style={{ marginBottom: 16 }}>
            We use Supabase for authentication and data storage, and Google for optional sign-in. These providers process data on our behalf under their own privacy and security practices.
          </p>
  
          <h4 style={{ color: 'var(--text)', marginTop: 20, marginBottom: 8 }}>Your control over your data</h4>
          <p style={{ marginBottom: 16 }}>
            You can update or delete most of your information directly in Settings. Deleting your account permanently removes your profile and associated data from our systems.
          </p>
  
          <h4 style={{ color: 'var(--text)', marginTop: 20, marginBottom: 8 }}>Contact</h4>
          <p style={{ marginBottom: 0 }}>
            Questions about this policy can be sent to the contact listed on our Terms of Service page.
          </p>
        </div>
      </div>
    )
  }